<?php

/**
 * BaseUsuario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property string $email
 * @property string $password
 * 
 * @method integer getId()       Returns the current record's "id" value
 * @method string  getNombre()   Returns the current record's "nombre" value
 * @method string  getEmail()    Returns the current record's "email" value
 * @method string  getPassword() Returns the current record's "password" value
 * @method Usuario setId()       Sets the current record's "id" value
 * @method Usuario setNombre()   Sets the current record's "nombre" value
 * @method Usuario setEmail()    Sets the current record's "email" value
 * @method Usuario setPassword() Sets the current record's "password" value
 * 
 * @package    SMProject
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUsuario extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('usuario');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             'notnull' => true,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             'notnull' => true,
             ));
        $this->hasColumn('password', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}