<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Prestamo', 'doctrine');

/**
 * BasePrestamo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $libro_id
 * @property integer $estudiante_id
 * @property date $fecha_prestamo
 * @property date $fecha_devolucion
 * @property boolean $devuelto
 * @property Libro $Libro
 * @property Estudiante $Estudiante
 * 
 * @method integer    getId()               Returns the current record's "id" value
 * @method integer    getLibroId()          Returns the current record's "libro_id" value
 * @method integer    getEstudianteId()     Returns the current record's "estudiante_id" value
 * @method date       getFechaPrestamo()    Returns the current record's "fecha_prestamo" value
 * @method date       getFechaDevolucion()  Returns the current record's "fecha_devolucion" value
 * @method boolean    getDevuelto()         Returns the current record's "devuelto" value
 * @method Libro      getLibro()            Returns the current record's "Libro" value
 * @method Estudiante getEstudiante()       Returns the current record's "Estudiante" value
 * @method Prestamo   setId()               Sets the current record's "id" value
 * @method Prestamo   setLibroId()          Sets the current record's "libro_id" value
 * @method Prestamo   setEstudianteId()     Sets the current record's "estudiante_id" value
 * @method Prestamo   setFechaPrestamo()    Sets the current record's "fecha_prestamo" value
 * @method Prestamo   setFechaDevolucion()  Sets the current record's "fecha_devolucion" value
 * @method Prestamo   setDevuelto()         Sets the current record's "devuelto" value
 * @method Prestamo   setLibro()            Sets the current record's "Libro" value
 * @method Prestamo   setEstudiante()       Sets the current record's "Estudiante" value
 * 
 * @package    SMProject
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePrestamo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('prestamos');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('libro_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('estudiante_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('fecha_prestamo', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('fecha_devolucion', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('devuelto', 'boolean', null, array(
             'type' => 'boolean',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Libro', array(
             'local' => 'libro_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Estudiante', array(
             'local' => 'estudiante_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}