<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Estudiante', 'doctrine');

/**
 * BaseEstudiante
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property string $apellidos
 * @property string $email
 * @property Doctrine_Collection $Prestamos
 * 
 * @method integer             getId()        Returns the current record's "id" value
 * @method string              getNombre()    Returns the current record's "nombre" value
 * @method string              getApellidos() Returns the current record's "apellidos" value
 * @method string              getEmail()     Returns the current record's "email" value
 * @method Doctrine_Collection getPrestamos() Returns the current record's "Prestamos" collection
 * @method Estudiante          setId()        Sets the current record's "id" value
 * @method Estudiante          setNombre()    Sets the current record's "nombre" value
 * @method Estudiante          setApellidos() Sets the current record's "apellidos" value
 * @method Estudiante          setEmail()     Sets the current record's "email" value
 * @method Estudiante          setPrestamos() Sets the current record's "Prestamos" collection
 * 
 * @package    SMProject
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEstudiante extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('estudiantes');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('apellidos', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Prestamo as Prestamos', array(
             'local' => 'id',
             'foreign' => 'estudiante_id'));
    }
}