<?php

/**
 * PrestamoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PrestamoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PrestamoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Prestamo');
    }
}