<?php
// auto-generated by sfSecurityConfigHandler
// date: 2025/03/26 07:33:03
$this->security = array (
  'login' => 
  array (
    'is_secure' => false,
  ),
  'register' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => false,
  ),
);
