# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url: /
  param: { module: prestamo, action: index }

default_index:
  url: /:module
  param: { action: index }

default:
  url: /:module/:action/*

# default rules

prestamolibro:
  url: /prestamo
  param: { module: prestamo, action: index }

prestamolibro_new:
  url: /prestamo/new
  param: { module: prestamo, action: new }

prestamolibro_edit:
  url: /prestamo/:id/edit
  param: { module: prestamo, action: edit }
  requirements: { id: \d+ }

estudiante:
  url: /estudiante
  param: { module: estudiante, action: index }

estudiante_new:
  url: /estudiante/new
  param: { module: estudiante, action: new }

estudiante_edit:
  url: /estudiante/:id/edit
  param: { module: estudiante, action: edit }
  requirements: { id: \d+ }

libro:
  url: /libro
  param: { module: libro, action: index }

libro_new:
  url: /libro/new
  param: { module: libro, action: new }

libro_edit:
  url: /libro/:id/edit
  param: { module: libro, action: edit }
  requirements: { id: \d+ }
