<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2025/03/25 19:57:13

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=ProjectSM',
  'username' => 'Prueba',
  'password' => 'f6j8s22.',
  'name' => 'doctrine',
)),);
